### ISSUE TITLE
messages between fleet adapter and fleet manager

### ISSUE THREAD

**Issue by imdalaf** [osrf/rmf_core#169] opened 2020-09-09 18:27 UTC
hi,
can i verify why is it that the rmf core integration diagram (https://github.com/osrf/rmf_core/blob/master/docs/rmf_core_integration_diagram.png) specify only 4 messages between fleet adapter and fleet manager? i would thought there are more than these 4 messages because it lacks:
  - the message to report to traffic schedule database the itineraries of the fleet
  - the message to report the position of the fleet
as pointed out in the 4 levels of control for fleet, these two messages are necessary.

**Comment by tanyouliang95** [comment] 2020-09-09 18:42
As was pointed out, there are more msgs in existence between the `fleet_adapters` and `rmf_core` (`rmf_traffic_msgs`). These msgs will mainly handle the negotiation and update of the traffic schedule databases. Also, according to the diagram, `fleet_state` msg is used to report the fleet position to the `fleet_adapter`.

**Comment by mxgrey** [comment] 2020-09-10 04:07
That diagram is out of date (we've replaced those message interfaces with an explicit C++ API that's discussed somewhat [here](https://github.com/osrf/rmf_core/issues/168#issuecomment-689964981)), but the basic idea is exactly as @tanyouliang95 described: The fleet adapter API will do most of the heavy lifting for communicating with the rest of RMF, and the individual fleets just need to satisfy a much simpler set of inputs and outputs than what's required for the overall traffic scheduling and negotiation system.

**Comment by imdalaf** [comment] 2020-09-10 19:57
thanks both for the replies. Is there any sample code or materials that could help me understand how to implement a fleet adapter and the interfacing portion of the fleet manager to the fleet adapter? Thanks.

**Comment by mxgrey** [comment] 2020-09-11 03:29
[Here's one example](https://github.com/osrf/rmf_core/blob/4f767627804aa3fe2085ebe632156e8338552d0b/rmf_fleet_adapter/src/full_control/main.cpp) of a "Full Control" fleet adapter that uses a ROS2 message API to interface with the `rmf_fleet_adapter` API. I don't recommend using the ROS2 message API of that fleet adapter because it's been deprecated due to not being expressive enough in various corner cases. But it may serve as a useful example for how to use the fleet adapter API.

There's a fleet adapter in development [here](https://github.com/osrf/fleet_adapter_mir/pull/1) that integrates with the MiR100 API using the [fleet adapter Python bindings](https://github.com/osrf/rmf_fleet_adapter_python). This fleet adapter is still under review and isn't tested yet, but the general idea behind it may be a good reference.

There aren't any examples that use the traffic light API yet. For the traffic light we're currently working on a mockup traffic light fleet manager for testing purposes, and then we'll begin integrating it with some real-world fleet manager APIs.

**Comment by imdalaf** [comment] 2020-10-20 05:00
Thanks for the reply. It seems that the communication between fleet adapter and fleet manager is carefully managed to keep it simple and generic using the 4 rmf messages. In that case, can i say that fleet adapter is pretty much generic and can be reused by another new fleet vendor with slight modification on the following steps listed out in the https://osrf.github.io/ros2multirobotbook/integration_fleets.html : 
- step 1 no need because reuse
- step 2 if no difference in approach to read runtime param, not required to change.
- step 3 loading the specific graph of fleet for the new vendor
- step 4 no need because reuse
- step 5 adding fleet of the new vendor
- step 6 no change required because the messages comms with fleet manager are generic rmf messages
- step 7 make changes to add new vendor's fleet
- step 8 no change required because the messages comms with fleet manager are generic rmf messages 

> The basic workflow of developing a fleet adapter is the following:
> 
> 1.Create an application that links to the rmf_fleet_adapter library.
> 2.Have the application read in runtime parameters in whatever way is desired (e.g. command line arguments, configuration file, ROS parameters, REST API calls, environment variables, etc).
> 3.Construct a route graph for each fleet that this application is providing the adapter for (a single adapter application can service any number of fleets), and/or parse the route graph from a YAML file using the rmf_fleet_adapter::agv::parse_graph utility.
> 4.Instantiate an rmf_fleet_adapter::agv::Adapter using Adapter::make(~) or Adapter::init_and_make(~).
> 5.Add the fleets that the application will be responsible for adapting, and save the rmf_fleet_adapter::agv::FleetUpdateHandlePtr instances that are passed back.
> 6.Implement the RobotCommandHandle class for the fleet manager API that is being adapted.
> 7.Add the robots that the adapter is responsible for controlling. The robots can be added based on the startup configuration, or they can be dynamically added during runtime as they are discovered over the fleet manager API (or both).
>    - When adding a robot, you will need to create a new instance of the custom RobotCommandHandle that you implemented.
>    - You will also need to provide a callback that will be triggered when the adapter is finished registering the robot. This callback will provide you with a new RobotUpdateHandle for your robot. It is imperative to save this update handle so you can use it to update the robot's position over time.
> 8.As new information arrives from the fleet manager API, use the collection of RobotUpdateHandle classes to keep the adapter up-to-date on the robots' positions.

**Comment by mxgrey** [comment] 2020-10-20 05:14
If you're suggesting copy/pasting the source code of an existing fleet adapter and then transplanting a new fleet's API into it, then sure, that's a perfectly acceptable thing to do, as long as the source code you're copying has a permissive license (everything from OSRC uses Apache-2.0, which is permissive) and you keep a copy of the original license. You can add your own license (including a closed-source license) on top of the permissive license, but legally speaking the permissive license of the code you're copying must remain with the source code, even if the permissive license will be "overpowered" by a closed-source license.

**Comment by imdalaf** [comment] 2020-10-20 18:06
@mxgrey thanks for the reply.

Actually i am coming for the angle of the work involved for a vendor to implement their own version of fleet adapter even if they have a workable version of the fleet adapter provided for them. Because the vendor is using a different fleet and running in a different site, using a different fleet manager.

Also, I am curious to confirm that there should be very minimum or none effort to switch fleet manager since the communication between fleet adapter and fleet manager is in ROS 2 using standard RMF defined messages (4 of them).

**Comment by mxgrey** [comment] 2020-10-21 03:53
> i am coming for the angle of the work involved for a vendor to implement their own version of fleet adapter even if they have a workable version of the fleet adapter provided for them.

I'm not sure how this is different from what I described, so I may need you to elaborate on this.

> there should be very minimum or none effort to switch fleet manager since the communication between fleet adapter and fleet manager is in ROS 2 using standard RMF defined messages (4 of them).

If you're talking about the messages here in [`rmf_fleet_msgs`](https://github.com/osrf/rmf_core/tree/master/rmf_fleet_msgs/msg), that API is considered deprecated. I would generally discourage using it because it has some known edge cases that cause undesirable behavior. It does mostly work and it *is* usable for demo purposes, but it may exhibit some intended behavior.

Instead for anything more important than a basic demo, I recommend using the C++ API that's described [here](https://osrf.github.io/ros2multirobotbook/integration_fleets.html). It may involve some more effort, but it will give more reliable results.

**Comment by mxgrey** [comment] 2021-02-01 06:19
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).

**Closed by mxgrey** 2021-02-01 06:19 UTC
