### ISSUE TITLE
Question about the tasks in rmf_core

### ISSUE THREAD

**Issue by MakinoharaShouko** [osrf/rmf_core#202] opened 2020-11-04 18:23 UTC
I am having some confusion on the implementation of `TaskManager.cpp` in `rmf_fleet_adapter`.

1. The `queue_task` method would check `_active_task` to see if the it should start the next task. However, I can have multiple tasks running at the same time. Is that done through multi threading? But I don't see synchronization in `TaskManager.cpp`.
2. Once a task is started, it's erased from the task queue in `TaskManager.cpp`. Then which component is responsible for keeping track of it?

I know these may be very stupid questions. Thank you very much for the reply!

**Comment by mxgrey** [comment] 2020-11-06 04:37
> Is that done through multi threading?

Yes, the fleet adapter is extremely multi-threaded.

> I don't see synchronization in `TaskManager.cpp`

This is by design. The multi-threading and synchronization is largely taken care of by [rxcpp](http://reactivex.io/RxCpp/). It's also worth noting that each `TaskManager` object is tied to exactly one robot, so there are actually as many `TaskManager` objects as there are robots, all running independently of each other. This design is being changed in the next minor release of RMF, but this is how it is if you're looking at the code right now.

> Once a task is started, it's erased from the task queue in `TaskManager.cpp`. Then which component is responsible for keeping track of it?

When a task is started, it gets erased from the queue and is [moved into the `_active_task`](https://github.com/osrf/rmf_core/blob/42ba1f8173b96e24f40eb52280b47ba088c9b7e0/rmf_fleet_adapter/src/rmf_fleet_adapter/TaskManager.cpp#L115) field in the `TaskManager`.

**Comment by mxgrey** [comment] 2021-02-01 06:24
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).

**Closed by mxgrey** 2021-02-01 06:24 UTC
