### ISSUE TITLE
Deviate from original route and move diagonally

### ISSUE THREAD

**Issue by Benjamin-Tan** [osrf/rmf_core#146] opened 2020-08-04 04:21 UTC
Version: latest master branch of commit 4d0dfca75b07c17078f88154e123a61e20b217a6

Using the demo launch file in rmf_demos, this behavior of moving diagonally is being observed across 2 different laptops. Below are the screenshots and gif for reference. It may bump into obstacles if it moves diagonally. Has anyone come across this issue before?

### Office environment
![Screenshot from 2020-08-03 15-20-23](https://user-images.githubusercontent.com/25479215/89249643-511a7f80-d645-11ea-8435-4b03d279d570.png)
![Screenshot from 2020-08-03 11-34-50](https://user-images.githubusercontent.com/25479215/89249648-55df3380-d645-11ea-99e9-ba89c431b0d3.png)

### Custom environment
![diagonal_motion](https://user-images.githubusercontent.com/25479215/89251894-cdfc2800-d64a-11ea-8e35-decd2f63be02.gif)

**Comment by mxgrey** [comment] 2020-08-04 08:00
Yep, this is a known behavior which results from using a deprecated fleet adapter API in simulation. We're in the process of updating the simulation fleets to use the new API, which should eliminate this unintended behavior.

In the meantime, if this is a critical issue, then we could add an interface to the deprecated API to reduce this behavior by allowing less tolerance for "lane merging" (which is what's happening here), but the trade-off is the simulation will be less robust to any situations where the robot diverges from its navigation graph.

**Comment by Jason-Zhou1** [comment] 2020-10-01 08:38
Hi mxgrey,
Would you please describe for us about the traffic management rules of the rmf_core? Thanks!

**Comment by mxgrey** [comment] 2020-10-01 09:33
@Jason-Zhou1 I'm not sure that this issue ticket is right place to be discussing that question. I would recommend [opening a new ticket](https://github.com/osrf/rmf_core/issues/new) to discuss that topic.

If you decide to follow up by opening a ticket, I might suggest being more specific about what you're trying to ask, because I'm afraid the question you've posed is so broad that I wouldn't know how to answer it. For one thing, the "traffic management" would be more accurately described as "traffic scheduling and negotiation". There aren't exactly "traffic rules" so much as a framework that allows fleets to see each other and negotiate with each other. That framework is designed to be extremely flexible, so the exact outcome of the traffic scheduling and negotiations will really depend on how the individual fleets have been integrated with RMF.

**Comment by Jason-Zhou1** [comment] 2020-10-01 10:11
Ok, I may need to reconsider how to ask this question. 
Thank you mxgrey.

**Comment by mxgrey** [comment] 2021-04-22 09:11
This issue should get resolved by migrating to the upcoming version of [`free_fleet`](https://github.com/open-rmf/free_fleet/pull/76). There isn't a compelling way to fix this in the legacy fleet adapter, so the issue will remain, and we'll encourage people to migrate when possible.

**Closed by mxgrey** 2021-04-22 09:11 UTC
